version: '3'
services:
    recorder:
        build: ./
        volumes:
            - ./records:/opt/vol
        privileged: true
        ulimits:
            nproc: 65535
            nofile:
                soft: 65535
                hard: 65535
